source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AvinAd_iOS_Example', :exclusive => true do
  pod "AvinAd_iOS", :path => "../"
end

target 'AvinAd_iOS_Tests', :exclusive => true do
  pod "AvinAd_iOS", :path => "../"

  
end
